### ISSUE TITLE
Please add event for addTrans

### ISSUE THREAD

**Issue by phildpearce** [CVM/Magento_GoogleTagManager#10]
Please add event for addTrans so that this can be used as a trigger and it replicates the legacy GA setup.

```
"event": "trackTrans" // Trigger transaction submission to GA via GTM 
```

}];

Note: using a dataLayer rule for transacitonId = not null is not an optimal setting, hence the event for trackTrans is strongly recommended.

Thanks

Phil.

**Comment by CVM** [comment]
Replicating a legacy setup is not something I'm aiming to do with this extension, but I do regret not adding a GTM event for when a transaction occurs from day one. In fact, for the next version I'd consider handling transactions with a dataLayer.push() rather than in the object at load time.

I'll add this to the roadmap with a more generic name (you won't always be tracking a transaction - you might want to use the transaction event for firing Google Adwords Conversion Tracking, for example).

``` JavaScript
dataLayer.push({'event':'transaction'});
```

**Comment by phildpearce** [comment]
Thanks :)
