### ISSUE TITLE
Suggestion to use window.dataLayer = window.dataLayer || [];

### ISSUE THREAD

**Issue by phildpearce** [CVM/Magento_GoogleTagManager#16]
Change 

<script>
dataLayer. = [{
...
}];
</script>

To...

<script>
window.dataLayer = window.dataLayer || [];
window.dataLayer.push({
...
        });
</script>

This reduces the chance of conflicts if dataLayer is called by onload video events later in the page.

Also using the "window." means that if the dataLayer loads in a frame it wont trigger or be overwritten.

**Comment by CVM** [comment]
GitHub seems to have eaten the code in your post, but I'd guess what you're saying is motivated by discussion in [this G+ post](https://plus.google.com/117298997433687198127/posts/cHyiQf5BKZJ).

Brian's code illustrates how to do a dataLayer.push() when you're not confident that the dataLayer is within current scope or think it might have been set to be something else other than an array. It can also help in situations where GTM has been declared in the wrong place, causing dataLayer.push() calls to occur prior to gtm.js loading.

This extension will always put gtm.js in the correct place, so dataLayer.push() calls anywhere in the body below this point should reliably queue up - you won't be able to push before the initial declaration.

In terms of scope, the dataLayer is declared globally, as normal. You can reference it from within other JavaScript functions without any problems, provided that it has not been overwritten, so prefixing with `window.` shouldn't be necessary. Example below:

``` HTML
<script>
  dataLayer = [];
</script>

...

<script>
  function fireEvent(eventName) {
    dataLayer.push({'event':eventName});
  }
  fireEvent('my_special_event');
</script>
```

Rather than add further code to every dataLayer.push() in order to guard against possible misuse, I feel that the edge case would be better dealt with by writing good code and not destroying it in the first place. No code within the extension will be doing this and it's very unlikely other extensions will be using the variable name for anything else.

**Comment by phildpearce** [comment]
This only effects video and social plugins that set a dataLayer later in the page, you are right, it is an edge case.

Here is the unmunchced code... 

window.dataLayer = window.dataLayer || [];
window.dataLayer.push({

Related post:
https://plus.google.com/111244485379930211802/posts/hYCyRyQ19vf

Problem...
// Set dataLayer
dataLayer = [{'page_virtual': '/virtual/OVERWRITTEN'}];
<script>

onclick="dataLayer = [{
   'event': 'onclick_pageview',
   'page_virtual': '/virtual/RETAINED'
}];"

Solution...



window.dataLayer = window.dataLayer || [];
window.dataLayer.push({
   'page_virtual': '/virtual/AAAAAA'
});



onclick="window.dataLayer = window.dataLayer || [];
window.dataLayer.push({
   'event': 'onclick_pageview',
   'page_virtual': '/virtual/BBBBBB'
});"

**Comment by CVM** [comment]
The post linked doesn't seem to relate to the edge case?

I guess if you're running your pageview on the gtm.load event, anything initially declared in the datalayer that was pushed a new value further down the page will be lost. But this is just an example of GTM misuse / poor implementation.

The same goes for overwriting the whole dataLayer var with an onclick. This is _really_ bad code that should be corrected - it's not something we should be trying to accommodate with the extension, as it encourages the continuation of a bad coding practice.

If there is a major social plugin that actually sets the datalayer as a new var (i.e. overwrites it, rather than using `dataLayer.push()`), I'd consider applying a workaround. But I won't be changing the extension to accommodate incorrect code written by one person.
