### ISSUE TITLE
Adwords Conversion Tracking

### ISSUE THREAD

**Issue by juggernaught** [CVM/Magento_GoogleTagManager#7]
Is there anything special that needs to be done to get the adwords conversion tracking to work?

I have already set up the tags in google tag manager.

Please any help would be appreciated.

**Comment by CVM** [comment]
To ensure it happens at the right time, your AdWords Conversion Tracking tag will need to fire on the same rule you use for your e-commerce transaction.

The Conversion ID and Conversion Label fields will be specific to your code - simply copy these parts into GTM from the snippet.

The Conversion Value should be the order total. Since we have e-commerce data in the dataLayer, if you create a dataLayer macro for "transactionTotal", you can then use this as the Conversion Value.
